# Special configuration file to run tests on Travis-CI via GitHub notifications
# See https://travis-ci.org/biopython/biopython/builds for results
#
# The tests are run via the coverage script, and if the tests pass the coverage
# information is pushed to https://codecov.io/github/biopython/biopython
#
# Note when testing Python 3, the 'python' command will invoke Python 3
# and similarly for PyPy too.

# Environment variables setup via the matrix
# - DEP = list of python packages to install via default pip install
# - COV = yes/no; should tests be run with coverage metric collection
# - OPT = options to run_tests.py such as --offline
language: python
matrix:
  include:
    - os: linux
      python: "2.6"
      env: DEP="rdflib reportlab psycopg2 mysql-python mysql-connector-python-rf unittest2 scipy" COV="yes" OPT="--offline"
    - os:linux:
      python: "2.7"
      env: DEP="rdflib reportlab psycopg2 mysql-python mysql-connector-python-rf networkx" COV="yes" OPT="--offline"
    - os: linux
      python: "3.3"
      env: DEP="psycopg2 mysql-connector-python-rf" COV="yes" OPT=""
    - os: linux
      python: "3.4"
      env: DEP="" COV="yes" OPT="--offline"
    - os linux:
      python: "3.5"
      env: DEP="rdflib reportlab psycopg2 mysql-connector-python-rf scipy matplotlib" COV="yes" OPT="--offline"
    - os: linux
      python: "pypy"
      env: DEP="rdflib mysql-connector-python-rf" COV="yes" OPT="--offline"
    - os: linux
      python: "pypy3"
      env: COV="no" OPT="--offline"
    - os: osx
      language: generic
      env: DEP="rdflib reportlab psycopg2 mysql-connector-python-rf scipy matplotlib" COV="yes" OPT="--offline"

sudo: false
addons:
  apt:
    packages:
    - bwa
    - clustalo
    - clustalw
    - emboss
    - mafft
    - muscle
    - probcons
    - samtools
    - wise

before_install:
# Perform the manual steps on osx to install python3 and activate venv
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
#Following for Linux and Mac OX X:
  - "pip install --upgrade pip"
  - "pip install --only-binary=numpy,scipy $DEP"
  - "if [[ $COV == 'yes' ]]; then pip install coverage; fi"


install:
#The yes is in case we get our prompt about missing NumPy
  - "/usr/bin/yes | python setup.py install"

before_script:
  - cd Tests
  - cp biosql.ini.sample biosql.ini

script:
#Using just coverage should match up to the current Python version:
  - "if [[ $COV == 'yes' ]]; then coverage run --source=Bio,BioSQL run_tests.py $OPT; fi"
  - "if [[ $COV != 'yes' ]]; then python run_tests.py $OPT; fi"

after_success:
#See https://codecov.io/ and https://github.com/codecov/example-python
  - "if [[ $COV == 'yes' ]]; then pip install codecov; fi"
  - "if [[ $COV == 'yes' ]]; then codecov; fi"

#The email defaults are too talkative
notifications:
  email: false
