# This is a special configuration file to run tests on Circle-CI via
# GitHub notifications when changes are committed.
#
# This file is not intended for end users of Biopython.

version: 2
jobs:
  build:
    docker:
      # A docker image with pdflatex preinstalled for speed
      # See https://github.com/samtools/hts-specs/tree/master/.circleci
      - image: htsspecs/circle-ci-image:0.6
    steps:
      - checkout
      - run:
          name: Setup hevea
          command: |
            echo -e '#!/bin/bash\necho "No hevea installed"' > ~/bin/hevea
            chmod a+x ~/bin/hevea
            echo $PATH
            ~/bin/hevea
            export PATH=$HOME/bin/:$PATH
            which hevea
      - run:
          name: Compile LaTeX Tutorial
          command: |
            make -C Doc/
