DROP RULE IF EXISTS rule_taxon_i ON taxon CASCADE;
DROP FUNCTION IF EXISTS constrain_taxon(integer);
DROP FUNCTION IF EXISTS unconstrain_taxon(integer);
DROP RULE IF EXISTS rule_term_synonym_i ON term_synonym CASCADE;
DROP RULE IF EXISTS rule_term_relationship_term_i2 ON term_relationship CASCADE;
DROP RULE IF EXISTS rule_term_relationship_term_i1 ON term_relationship CASCADE;
DROP RULE IF EXISTS rule_term_relationship_i ON term_relationship CASCADE;
DROP RULE IF EXISTS rule_term_path_i ON term_path CASCADE;
DROP RULE IF EXISTS rule_term_dbxref_i ON term_dbxref CASCADE;
DROP RULE IF EXISTS rule_term_i2 ON term CASCADE;
DROP RULE IF EXISTS rule_term_i1 ON term CASCADE;
DROP RULE IF EXISTS rule_taxon_name_i ON taxon_name CASCADE;
DROP RULE IF EXISTS rule_taxon_i ON taxon CASCADE;
DROP RULE IF EXISTS rule_seqfeature_relationship_i ON seqfeature_relationship CASCADE;
DROP RULE IF EXISTS rule_seqfeature_qualifier_value_i ON seqfeature_qualifier_value CASCADE;
DROP RULE IF EXISTS rule_seqfeature_path_i ON seqfeature_path CASCADE;
DROP RULE IF EXISTS rule_seqfeature_dbxref_i ON seqfeature_dbxref CASCADE;
DROP RULE IF EXISTS rule_seqfeature_i ON seqfeature CASCADE;
DROP RULE IF EXISTS rule_reference_i2 ON reference CASCADE;
DROP RULE IF EXISTS rule_reference_i1 ON reference CASCADE;
DROP RULE IF EXISTS rule_ontology_i ON ontology CASCADE;
DROP RULE IF EXISTS rule_location_qualifier_value_i ON location_qualifier_value CASCADE;
DROP RULE IF EXISTS rule_location_i ON location CASCADE;
DROP RULE IF EXISTS rule_dbxref_qualifier_value_i ON dbxref_qualifier_value CASCADE;
DROP RULE IF EXISTS rule_dbxref_i ON dbxref CASCADE;
DROP RULE IF EXISTS rule_comment_i ON comment CASCADE;
DROP RULE IF EXISTS rule_biosequence_i ON biosequence CASCADE;
DROP RULE IF EXISTS rule_bioentry_relationship_i ON bioentry_relationship CASCADE;
DROP RULE IF EXISTS rule_bioentry_reference_i ON bioentry_reference CASCADE;
DROP RULE IF EXISTS rule_bioentry_qualifier_value_i ON bioentry_qualifier_value CASCADE;
DROP RULE IF EXISTS rule_bioentry_path_i ON bioentry_path CASCADE;
DROP RULE IF EXISTS rule_bioentry_dbxref_i ON bioentry_dbxref CASCADE;
DROP RULE IF EXISTS rule_biodatabase_i ON biodatabase CASCADE;
DROP RULE IF EXISTS rule_bioentry_i2 ON bioentry CASCADE;
DROP RULE IF EXISTS rule_bioentry_i1 ON bioentry CASCADE;
#DROP INDEX locationqual_trm ON location_qualifier_value ( term_id ) CASCADE; 
DROP TABLE IF EXISTS location_qualifier_value CASCADE;
#DROP INDEX seqfeatureloc_trm ON location ( term_id ) CASCADE; 
#DROP INDEX seqfeatureloc_dbx ON location ( dbxref_id ) CASCADE; 
#DROP INDEX seqfeatureloc_start ON location ( start_pos, end_pos ) CASCADE; 
DROP TABLE IF EXISTS location CASCADE;
DROP SEQUENCE location_pk_seq CASCADE;
#DROP INDEX feadblink_dbx ON seqfeature_dbxref ( dbxref_id ) CASCADE; 
DROP TABLE IF EXISTS seqfeature_dbxref CASCADE;
#DROP INDEX seqfeaturequal_trm ON seqfeature_qualifier_value ( term_id ) CASCADE; 
DROP TABLE IF EXISTS seqfeature_qualifier_value CASCADE;
#DROP INDEX seqfeaturepath_child ON seqfeature_path ( subject_seqfeature_id ) CASCADE;
#DROP INDEX seqfeaturepath_trm ON seqfeature_path ( term_id ) CASCADE; 
DROP TABLE IF EXISTS seqfeature_path CASCADE;
#DROP INDEX seqfeaturerel_child ON seqfeature_relationship ( subject_seqfeature_id ) CASCADE; 
#DROP INDEX seqfeaturerel_trm ON seqfeature_relationship ( term_id ) CASCADE; 
DROP TABLE IF EXISTS seqfeature_relationship CASCADE;
DROP SEQUENCE seqfeature_relationship_pk_seq CASCADE;
#DROP INDEX seqfeature_fsrc ON seqfeature ( source_term_id ) CASCADE; 
#DROP INDEX seqfeature_trm ON seqfeature ( type_term_id ) CASCADE; 
DROP TABLE IF EXISTS seqfeature CASCADE;
DROP SEQUENCE seqfeature_pk_seq CASCADE;
#DROP INDEX bioentryqual_trm ON bioentry_qualifier_value ( term_id ) CASCADE; 
DROP TABLE IF EXISTS bioentry_qualifier_value CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP SEQUENCE comment_pk_seq CASCADE;
#DROP INDEX bioentryref_ref ON bioentry_reference ( reference_id ) CASCADE; 
DROP TABLE IF EXISTS bioentry_reference CASCADE;
DROP TABLE IF EXISTS reference CASCADE;
DROP SEQUENCE reference_pk_seq CASCADE;
#DROP INDEX dblink_dbx ON bioentry_dbxref ( dbxref_id ) CASCADE; 
DROP TABLE IF EXISTS bioentry_dbxref CASCADE;
#DROP INDEX dbxrefqual_trm ON dbxref_qualifier_value ( term_id ) CASCADE; 
#DROP INDEX dbxrefqual_dbx ON dbxref_qualifier_value ( dbxref_id ) CASCADE; 
DROP TABLE IF EXISTS dbxref_qualifier_value CASCADE;
#DROP INDEX dbxref_db ON dbxref ( dbname ) CASCADE; 
DROP TABLE IF EXISTS dbxref CASCADE;
DROP SEQUENCE dbxref_pk_seq CASCADE;
DROP TABLE IF EXISTS biosequence CASCADE;
#DROP INDEX bioentrypath_child ON bioentry_path ( subject_bioentry_id ) CASCADE; 
#DROP INDEX bioentrypath_trm ON bioentry_path ( term_id ) CASCADE; 
DROP TABLE IF EXISTS bioentry_path CASCADE;
#DROP INDEX bioentryrel_child ON bioentry_relationship (subject_bioentry_id) CASCADE;
#DROP INDEX bioentryrel_trm ON bioentry_relationship ( term_id ) CASCADE; 
DROP TABLE IF EXISTS bioentry_relationship CASCADE;
DROP SEQUENCE bioentry_relationship_pk_seq CASCADE;
#DROP INDEX bioentry_tax ON bioentry ( taxon_id ) CASCADE; 
#DROP INDEX bioentry_db ON bioentry ( biodatabase_id ) CASCADE; 
#DROP INDEX bioentry_name ON bioentry ( name ) CASCADE; 
DROP TABLE IF EXISTS bioentry CASCADE;
DROP SEQUENCE bioentry_pk_seq CASCADE;
#DROP INDEX trmpath_ontid ON term_path ( ontology_id ) CASCADE; 
#DROP INDEX trmpath_objectid ON term_path ( object_term_id ) CASCADE; 
#DROP INDEX trmpath_predicateid ON term_path ( predicate_term_id ) CASCADE; 
DROP TABLE IF EXISTS term_path CASCADE;
DROP SEQUENCE term_path_pk_seq CASCADE;
DROP TABLE IF EXISTS term_relationship_term CASCADE;
#DROP INDEX trmrel_ontid ON term_relationship ( ontology_id ) CASCADE; 
#DROP INDEX trmrel_objectid ON term_relationship ( object_term_id ) CASCADE; 
#DROP INDEX trmrel_predicateid ON term_relationship ( predicate_term_id ) CASCADE; 
DROP TABLE IF EXISTS term_relationship CASCADE;
DROP SEQUENCE term_relationship_pk_seq CASCADE;
#DROP INDEX trmdbxref_dbxrefid ON term_dbxref ( dbxref_id ) CASCADE; 
DROP TABLE IF EXISTS term_dbxref CASCADE;
DROP TABLE IF EXISTS term_synonym CASCADE;
#DROP INDEX term_ont ON term ( ontology_id ) CASCADE; 
DROP TABLE IF EXISTS term CASCADE;
DROP SEQUENCE term_pk_seq CASCADE;
DROP TABLE IF EXISTS ontology CASCADE; 
DROP SEQUENCE ontology_pk_seq CASCADE;
#DROP INDEX taxnamename ON taxon_name ( name ) CASCADE; 
#DROP INDEX taxnametaxonid ON taxon_name ( taxon_id ) CASCADE; 
DROP TABLE IF EXISTS taxon_name CASCADE;
#DROP INDEX taxparent ON taxon ( parent_taxon_id ) CASCADE; 
DROP TABLE IF EXISTS taxon CASCADE;
DROP SEQUENCE taxon_pk_seq CASCADE;
#DROP INDEX db_auth ON CASCADE;
DROP TABLE IF EXISTS biodatabase CASCADE;
DROP SEQUENCE IF EXISTS biodatabase_pk_seq CASCADE;
